### ISSUE TITLE
what means "multiple backends" in README

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#141]
what means "multiple backends" in README ? please.. 

(i hope means any RDBMS for users or similar, not only plain one)

**Comment by ViBiOh** [comment]
The "multiple storage backend" refers to where the files are stored. Fibr stores every information it needs in files, because it manages files. I don't plan to store metadatas in external databases because it will add a dependency, for the same reason I don't add a Redis for shared/distributed storage of metadatas. The goal of this project is to be simple to manage.

**Comment by mckaygerhard** [comment]
closing #141 cos all information provides makes sense and is very clear! i will made a pull request with better documentation in "docs" directory

> Fibr stores every information it needs in file

well i must define that for a good article, i guess in a .json directory in a json file right? 

> it manages files. I don't plan to store metadatas in external databases because it will add a dependency, 

makes sense and is reasonable closing this !

> for the same reason I don't add a Redis for shared/distributed storage of metadatas. The goal of this project is to be simple to manage.

THANKS GOD AND ALIENS ! HELL YEAH!
