### ISSUE TITLE
how to disable image and video thumbs ?

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#144]
after running new versio got too many logs about "`dial tcp: lookup image on 10.1.193.13:53: no such host`" so i search on selft binary and got this options :

```
  -thumbnailImageURL string
    	[thumbnail] Imaginary URL {FIBR_THUMBNAIL_IMAGE_URL} (default "http://image:9000")
  -thumbnailVideoURL string
    	[thumbnail] Video Thumbnail URL {FIBR_THUMBNAIL_VIDEO_URL} (default "http://video:1080")
```

but no documentation about. any help to propperty configured **to disable it?**

**Comment by mckaygerhard** [comment]
also there's another backend for? it seems bit complicated the instalation of thunmbs! puff

**Comment by ViBiOh** [comment]
You can set this two options to blank and there will be no thumbs generation. The values are here by default because most the time, people want thumbnails.

I don't plan to add another thumbnails conversion backend. Many of pictures thumbnails tools are "on-the-fly" image proxy that want direct access to filesystem.
